In [1]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25.0, np.nan, 30.0, 22.0, np.nan],
    'City': ['London', 'Paris', np.nan, 'New York', 'Tokyo'],
    'Salary': [50000, 60000, np.nan, 45000, 80000],
    'Joined_Date': [pd.Timestamp('2023-01-15'), pd.NaT, pd.Timestamp('2022-05-12'), pd.Timestamp('2024-08-01'), pd.Timestamp('2021-11-30')]
}

# Create the DataFrame
df = pd.DataFrame(data)

In [2]:
df.isna()

    Name    Age   City  Salary  Joined_Date
0  False  False  False   False        False
1  False   True  False   False         True
2  False  False   True    True        False
3  False  False  False   False        False
4  False   True  False   False        False

In [9]:
df

      Name   Age      City   Salary Joined_Date
0    Alice  25.0    London  50000.0  2023-01-15
1      Bob   NaN     Paris  60000.0         NaT
2  Charlie  30.0       NaN      NaN  2022-05-12
3    David  22.0  New York  45000.0  2024-08-01
4      Eva   NaN     Tokyo  80000.0  2021-11-30

In [4]:
df.isna().any()

Name           False
Age             True
City            True
Salary          True
Joined_Date     True
dtype: bool

In [8]:
print(df.isna().any().any())

True

In [10]:
print(df.isna().any().sum())

4